services:
  - type: web
    name: hcm_backend
    runtime: python
    plan: free

    buildCommand: "./build.sh"

    startCommand: "gunicorn HCM.asgi:application -k uvicorn.workers.UvicornWorker"

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5

      - key: SECRET_KEY
        sync: false

      - key: DEBUG
        value: "False"

      - key: DATABASE_URL
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_KEY
        sync: false